<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SidebarPermission extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $permissions = array(
  array('id' => '819','module' => NULL,'sidebar_menu' => 'student_info','old_id' => NULL,'section_id' => '1','parent_id' => '0','name' => 'Assign Extra Curricular Class','route' => 'student.assign-extra-curricular','parent_route' => 'student_info','type' => '2','lang_name' => 'student.assign_extra_curricular','icon' => NULL,'svg' => NULL,'status' => '1','menu_status' => '1','position' => '16','is_saas' => '0','relate_to_child' => '0','is_menu' => '1','is_admin' => '1','is_teacher' => '0','is_student' => '0','is_parent' => '0','created_by' => '1','updated_by' => '1','permission_section' => '0','alternate_module' => NULL,'user_id' => NULL,'school_id' => '1','created_at' => NULL,'updated_at' => NULL),
  array('id' => '820','module' => NULL,'sidebar_menu' => NULL,'old_id' => NULL,'section_id' => '1','parent_id' => '0','name' => 'Dashboard','route' => 'dashboard_section','parent_route' => NULL,'type' => NULL,'lang_name' => 'common.dashboard','icon' => NULL,'svg' => NULL,'status' => '1','menu_status' => '1','position' => '1','is_saas' => '0','relate_to_child' => '0','is_menu' => '1','is_admin' => '1','is_teacher' => '0','is_student' => '0','is_parent' => '0','created_by' => '1','updated_by' => '1','permission_section' => '1','alternate_module' => NULL,'user_id' => '13','school_id' => '1','created_at' => '2023-11-08 15:23:57','updated_at' => '2023-11-08 15:23:57'),
  array('id' => '821','module' => NULL,'sidebar_menu' => NULL,'old_id' => NULL,'section_id' => '1','parent_id' => '0','name' => 'Administration','route' => 'administration_section','parent_route' => NULL,'type' => NULL,'lang_name' => 'common.Administration','icon' => NULL,'svg' => NULL,'status' => '1','menu_status' => '1','position' => '8','is_saas' => '0','relate_to_child' => '0','is_menu' => '1','is_admin' => '1','is_teacher' => '0','is_student' => '0','is_parent' => '0','created_by' => '1','updated_by' => '1','permission_section' => '1','alternate_module' => NULL,'user_id' => '13','school_id' => '1','created_at' => '2023-11-08 15:23:57','updated_at' => '2023-11-08 15:23:57'),
  array('id' => '822','module' => NULL,'sidebar_menu' => NULL,'old_id' => NULL,'section_id' => '1','parent_id' => '0','name' => 'Student','route' => 'student_section','parent_route' => NULL,'type' => NULL,'lang_name' => 'common.student','icon' => NULL,'svg' => NULL,'status' => '1','menu_status' => '1','position' => '8','is_saas' => '0','relate_to_child' => '0','is_menu' => '1','is_admin' => '1','is_teacher' => '0','is_student' => '0','is_parent' => '0','created_by' => '1','updated_by' => '1','permission_section' => '1','alternate_module' => NULL,'user_id' => '13','school_id' => '1','created_at' => '2023-11-08 15:23:57','updated_at' => '2023-11-08 15:23:57'),
  array('id' => '823','module' => NULL,'sidebar_menu' => NULL,'old_id' => NULL,'section_id' => '1','parent_id' => '0','name' => 'Exam','route' => 'exam_section','parent_route' => NULL,'type' => NULL,'lang_name' => 'common.exam','icon' => NULL,'svg' => NULL,'status' => '1','menu_status' => '1','position' => '8','is_saas' => '0','relate_to_child' => '0','is_menu' => '1','is_admin' => '1','is_teacher' => '0','is_student' => '0','is_parent' => '0','created_by' => '1','updated_by' => '1','permission_section' => '1','alternate_module' => NULL,'user_id' => '13','school_id' => '1','created_at' => '2023-11-08 15:23:57','updated_at' => '2023-11-08 15:23:57'),
  array('id' => '824','module' => NULL,'sidebar_menu' => NULL,'old_id' => NULL,'section_id' => '1','parent_id' => '0','name' => 'Hr','route' => 'hr_section','parent_route' => NULL,'type' => NULL,'lang_name' => 'common.hr','icon' => NULL,'svg' => NULL,'status' => '1','menu_status' => '1','position' => '8','is_saas' => '0','relate_to_child' => '0','is_menu' => '1','is_admin' => '1','is_teacher' => '0','is_student' => '0','is_parent' => '0','created_by' => '1','updated_by' => '1','permission_section' => '1','alternate_module' => NULL,'user_id' => '13','school_id' => '1','created_at' => '2023-11-08 15:23:57','updated_at' => '2023-11-08 15:23:57'),
  array('id' => '825','module' => NULL,'sidebar_menu' => NULL,'old_id' => NULL,'section_id' => '1','parent_id' => '0','name' => 'Accounts','route' => 'accounts_section','parent_route' => NULL,'type' => NULL,'lang_name' => 'common.accounts','icon' => NULL,'svg' => NULL,'status' => '1','menu_status' => '1','position' => '8','is_saas' => '0','relate_to_child' => '0','is_menu' => '1','is_admin' => '1','is_teacher' => '0','is_student' => '0','is_parent' => '0','created_by' => '1','updated_by' => '1','permission_section' => '1','alternate_module' => NULL,'user_id' => '13','school_id' => '1','created_at' => '2023-11-08 15:23:57','updated_at' => '2023-11-08 15:23:57'),
  array('id' => '826','module' => NULL,'sidebar_menu' => NULL,'old_id' => NULL,'section_id' => '1','parent_id' => '0','name' => 'Utilities','route' => 'utilities_section','parent_route' => NULL,'type' => NULL,'lang_name' => 'common.Utilities','icon' => NULL,'svg' => NULL,'status' => '1','menu_status' => '1','position' => '8','is_saas' => '0','relate_to_child' => '0','is_menu' => '1','is_admin' => '1','is_teacher' => '0','is_student' => '0','is_parent' => '0','created_by' => '1','updated_by' => '1','permission_section' => '1','alternate_module' => NULL,'user_id' => '13','school_id' => '1','created_at' => '2023-11-08 15:23:57','updated_at' => '2023-11-08 15:23:57'),
  array('id' => '827','module' => NULL,'sidebar_menu' => NULL,'old_id' => NULL,'section_id' => '1','parent_id' => '0','name' => 'Report','route' => 'report_section','parent_route' => NULL,'type' => NULL,'lang_name' => 'common.report_section','icon' => NULL,'svg' => NULL,'status' => '1','menu_status' => '1','position' => '8','is_saas' => '0','relate_to_child' => '0','is_menu' => '1','is_admin' => '1','is_teacher' => '0','is_student' => '0','is_parent' => '0','created_by' => '1','updated_by' => '1','permission_section' => '1','alternate_module' => NULL,'user_id' => '13','school_id' => '1','created_at' => '2023-11-08 15:23:57','updated_at' => '2023-11-08 15:23:57'),
  array('id' => '828','module' => NULL,'sidebar_menu' => NULL,'old_id' => NULL,'section_id' => '1','parent_id' => '0','name' => 'Settings Section','route' => 'settings_section','parent_route' => NULL,'type' => NULL,'lang_name' => 'common.settings_section','icon' => NULL,'svg' => NULL,'status' => '1','menu_status' => '1','position' => '8','is_saas' => '0','relate_to_child' => '0','is_menu' => '1','is_admin' => '1','is_teacher' => '0','is_student' => '0','is_parent' => '0','created_by' => '1','updated_by' => '1','permission_section' => '1','alternate_module' => NULL,'user_id' => '13','school_id' => '1','created_at' => '2023-11-08 15:23:57','updated_at' => '2023-11-08 15:23:57'),
  array('id' => '829','module' => NULL,'sidebar_menu' => NULL,'old_id' => NULL,'section_id' => '1','parent_id' => '0','name' => 'Module','route' => 'module_section','parent_route' => NULL,'type' => NULL,'lang_name' => 'common.module','icon' => NULL,'svg' => NULL,'status' => '1','menu_status' => '1','position' => '10','is_saas' => '0','relate_to_child' => '0','is_menu' => '1','is_admin' => '1','is_teacher' => '0','is_student' => '0','is_parent' => '0','created_by' => '1','updated_by' => '1','permission_section' => '1','alternate_module' => NULL,'user_id' => '13','school_id' => '1','created_at' => '2023-11-08 15:23:57','updated_at' => '2023-11-08 15:23:57'),
  array('id' => '830','module' => NULL,'sidebar_menu' => NULL,'old_id' => NULL,'section_id' => '1','parent_id' => '0','name' => 'Dashboard','route' => 'dashboard_section','parent_route' => NULL,'type' => NULL,'lang_name' => 'common.dashboard','icon' => NULL,'svg' => NULL,'status' => '1','menu_status' => '1','position' => '1','is_saas' => '0','relate_to_child' => '0','is_menu' => '1','is_admin' => '1','is_teacher' => '0','is_student' => '0','is_parent' => '0','created_by' => '1','updated_by' => '1','permission_section' => '1','alternate_module' => NULL,'user_id' => '2','school_id' => '1','created_at' => '2023-11-09 13:35:15','updated_at' => '2023-11-09 13:35:15'),
  array('id' => '831','module' => NULL,'sidebar_menu' => NULL,'old_id' => NULL,'section_id' => '1','parent_id' => '0','name' => 'Administration','route' => 'administration_section','parent_route' => NULL,'type' => NULL,'lang_name' => 'common.Administration','icon' => NULL,'svg' => NULL,'status' => '1','menu_status' => '1','position' => '8','is_saas' => '0','relate_to_child' => '0','is_menu' => '1','is_admin' => '1','is_teacher' => '0','is_student' => '0','is_parent' => '0','created_by' => '1','updated_by' => '1','permission_section' => '1','alternate_module' => NULL,'user_id' => '2','school_id' => '1','created_at' => '2023-11-09 13:35:15','updated_at' => '2023-11-09 13:35:15'),
  array('id' => '832','module' => NULL,'sidebar_menu' => NULL,'old_id' => NULL,'section_id' => '1','parent_id' => '0','name' => 'Student','route' => 'student_section','parent_route' => NULL,'type' => NULL,'lang_name' => 'common.student','icon' => NULL,'svg' => NULL,'status' => '1','menu_status' => '1','position' => '8','is_saas' => '0','relate_to_child' => '0','is_menu' => '1','is_admin' => '1','is_teacher' => '0','is_student' => '0','is_parent' => '0','created_by' => '1','updated_by' => '1','permission_section' => '1','alternate_module' => NULL,'user_id' => '2','school_id' => '1','created_at' => '2023-11-09 13:35:15','updated_at' => '2023-11-09 13:35:15'),
  array('id' => '833','module' => NULL,'sidebar_menu' => NULL,'old_id' => NULL,'section_id' => '1','parent_id' => '0','name' => 'Exam','route' => 'exam_section','parent_route' => NULL,'type' => NULL,'lang_name' => 'common.exam','icon' => NULL,'svg' => NULL,'status' => '1','menu_status' => '1','position' => '8','is_saas' => '0','relate_to_child' => '0','is_menu' => '1','is_admin' => '1','is_teacher' => '0','is_student' => '0','is_parent' => '0','created_by' => '1','updated_by' => '1','permission_section' => '1','alternate_module' => NULL,'user_id' => '2','school_id' => '1','created_at' => '2023-11-09 13:35:15','updated_at' => '2023-11-09 13:35:15'),
  array('id' => '834','module' => NULL,'sidebar_menu' => NULL,'old_id' => NULL,'section_id' => '1','parent_id' => '0','name' => 'Hr','route' => 'hr_section','parent_route' => NULL,'type' => NULL,'lang_name' => 'common.hr','icon' => NULL,'svg' => NULL,'status' => '1','menu_status' => '1','position' => '8','is_saas' => '0','relate_to_child' => '0','is_menu' => '1','is_admin' => '1','is_teacher' => '0','is_student' => '0','is_parent' => '0','created_by' => '1','updated_by' => '1','permission_section' => '1','alternate_module' => NULL,'user_id' => '2','school_id' => '1','created_at' => '2023-11-09 13:35:15','updated_at' => '2023-11-09 13:35:15'),
  array('id' => '835','module' => NULL,'sidebar_menu' => NULL,'old_id' => NULL,'section_id' => '1','parent_id' => '0','name' => 'Accounts','route' => 'accounts_section','parent_route' => NULL,'type' => NULL,'lang_name' => 'common.accounts','icon' => NULL,'svg' => NULL,'status' => '1','menu_status' => '1','position' => '8','is_saas' => '0','relate_to_child' => '0','is_menu' => '1','is_admin' => '1','is_teacher' => '0','is_student' => '0','is_parent' => '0','created_by' => '1','updated_by' => '1','permission_section' => '1','alternate_module' => NULL,'user_id' => '2','school_id' => '1','created_at' => '2023-11-09 13:35:15','updated_at' => '2023-11-09 13:35:15'),
  array('id' => '836','module' => NULL,'sidebar_menu' => NULL,'old_id' => NULL,'section_id' => '1','parent_id' => '0','name' => 'Utilities','route' => 'utilities_section','parent_route' => NULL,'type' => NULL,'lang_name' => 'common.Utilities','icon' => NULL,'svg' => NULL,'status' => '1','menu_status' => '1','position' => '8','is_saas' => '0','relate_to_child' => '0','is_menu' => '1','is_admin' => '1','is_teacher' => '0','is_student' => '0','is_parent' => '0','created_by' => '1','updated_by' => '1','permission_section' => '1','alternate_module' => NULL,'user_id' => '2','school_id' => '1','created_at' => '2023-11-09 13:35:15','updated_at' => '2023-11-09 13:35:15'),
  array('id' => '837','module' => NULL,'sidebar_menu' => NULL,'old_id' => NULL,'section_id' => '1','parent_id' => '0','name' => 'Report','route' => 'report_section','parent_route' => NULL,'type' => NULL,'lang_name' => 'common.report_section','icon' => NULL,'svg' => NULL,'status' => '1','menu_status' => '1','position' => '8','is_saas' => '0','relate_to_child' => '0','is_menu' => '1','is_admin' => '1','is_teacher' => '0','is_student' => '0','is_parent' => '0','created_by' => '1','updated_by' => '1','permission_section' => '1','alternate_module' => NULL,'user_id' => '2','school_id' => '1','created_at' => '2023-11-09 13:35:15','updated_at' => '2023-11-09 13:35:15'),
  array('id' => '838','module' => NULL,'sidebar_menu' => NULL,'old_id' => NULL,'section_id' => '1','parent_id' => '0','name' => 'Settings Section','route' => 'settings_section','parent_route' => NULL,'type' => NULL,'lang_name' => 'common.settings_section','icon' => NULL,'svg' => NULL,'status' => '1','menu_status' => '1','position' => '8','is_saas' => '0','relate_to_child' => '0','is_menu' => '1','is_admin' => '1','is_teacher' => '0','is_student' => '0','is_parent' => '0','created_by' => '1','updated_by' => '1','permission_section' => '1','alternate_module' => NULL,'user_id' => '2','school_id' => '1','created_at' => '2023-11-09 13:35:15','updated_at' => '2023-11-09 13:35:15'),
  array('id' => '839','module' => NULL,'sidebar_menu' => NULL,'old_id' => NULL,'section_id' => '1','parent_id' => '0','name' => 'Module','route' => 'module_section','parent_route' => NULL,'type' => NULL,'lang_name' => 'common.module','icon' => NULL,'svg' => NULL,'status' => '1','menu_status' => '1','position' => '10','is_saas' => '0','relate_to_child' => '0','is_menu' => '1','is_admin' => '1','is_teacher' => '0','is_student' => '0','is_parent' => '0','created_by' => '1','updated_by' => '1','permission_section' => '1','alternate_module' => NULL,'user_id' => '2','school_id' => '1','created_at' => '2023-11-09 13:35:15','updated_at' => '2023-11-09 13:35:15'),
  array('id' => '840','module' => NULL,'sidebar_menu' => NULL,'old_id' => NULL,'section_id' => '1','parent_id' => '0','name' => 'Dashboard','route' => 'dashboard_section','parent_route' => NULL,'type' => NULL,'lang_name' => 'common.dashboard','icon' => NULL,'svg' => NULL,'status' => '1','menu_status' => '1','position' => '1','is_saas' => '0','relate_to_child' => '0','is_menu' => '1','is_admin' => '1','is_teacher' => '0','is_student' => '0','is_parent' => '0','created_by' => '1','updated_by' => '1','permission_section' => '1','alternate_module' => NULL,'user_id' => '46','school_id' => '1','created_at' => '2023-11-15 10:53:33','updated_at' => '2023-11-15 10:53:33'),
  array('id' => '841','module' => NULL,'sidebar_menu' => NULL,'old_id' => NULL,'section_id' => '1','parent_id' => '0','name' => 'Administration','route' => 'administration_section','parent_route' => NULL,'type' => NULL,'lang_name' => 'common.Administration','icon' => NULL,'svg' => NULL,'status' => '1','menu_status' => '1','position' => '8','is_saas' => '0','relate_to_child' => '0','is_menu' => '1','is_admin' => '1','is_teacher' => '0','is_student' => '0','is_parent' => '0','created_by' => '1','updated_by' => '1','permission_section' => '1','alternate_module' => NULL,'user_id' => '46','school_id' => '1','created_at' => '2023-11-15 10:53:33','updated_at' => '2023-11-15 10:53:33'),
  array('id' => '842','module' => NULL,'sidebar_menu' => NULL,'old_id' => NULL,'section_id' => '1','parent_id' => '0','name' => 'Student','route' => 'student_section','parent_route' => NULL,'type' => NULL,'lang_name' => 'common.student','icon' => NULL,'svg' => NULL,'status' => '1','menu_status' => '1','position' => '8','is_saas' => '0','relate_to_child' => '0','is_menu' => '1','is_admin' => '1','is_teacher' => '0','is_student' => '0','is_parent' => '0','created_by' => '1','updated_by' => '1','permission_section' => '1','alternate_module' => NULL,'user_id' => '46','school_id' => '1','created_at' => '2023-11-15 10:53:33','updated_at' => '2023-11-15 10:53:33'),
  array('id' => '843','module' => NULL,'sidebar_menu' => NULL,'old_id' => NULL,'section_id' => '1','parent_id' => '0','name' => 'Exam','route' => 'exam_section','parent_route' => NULL,'type' => NULL,'lang_name' => 'common.exam','icon' => NULL,'svg' => NULL,'status' => '1','menu_status' => '1','position' => '8','is_saas' => '0','relate_to_child' => '0','is_menu' => '1','is_admin' => '1','is_teacher' => '0','is_student' => '0','is_parent' => '0','created_by' => '1','updated_by' => '1','permission_section' => '1','alternate_module' => NULL,'user_id' => '46','school_id' => '1','created_at' => '2023-11-15 10:53:33','updated_at' => '2023-11-15 10:53:33'),
  array('id' => '844','module' => NULL,'sidebar_menu' => NULL,'old_id' => NULL,'section_id' => '1','parent_id' => '0','name' => 'Hr','route' => 'hr_section','parent_route' => NULL,'type' => NULL,'lang_name' => 'common.hr','icon' => NULL,'svg' => NULL,'status' => '1','menu_status' => '1','position' => '8','is_saas' => '0','relate_to_child' => '0','is_menu' => '1','is_admin' => '1','is_teacher' => '0','is_student' => '0','is_parent' => '0','created_by' => '1','updated_by' => '1','permission_section' => '1','alternate_module' => NULL,'user_id' => '46','school_id' => '1','created_at' => '2023-11-15 10:53:33','updated_at' => '2023-11-15 10:53:33'),
  array('id' => '845','module' => NULL,'sidebar_menu' => NULL,'old_id' => NULL,'section_id' => '1','parent_id' => '0','name' => 'Accounts','route' => 'accounts_section','parent_route' => NULL,'type' => NULL,'lang_name' => 'common.accounts','icon' => NULL,'svg' => NULL,'status' => '1','menu_status' => '1','position' => '8','is_saas' => '0','relate_to_child' => '0','is_menu' => '1','is_admin' => '1','is_teacher' => '0','is_student' => '0','is_parent' => '0','created_by' => '1','updated_by' => '1','permission_section' => '1','alternate_module' => NULL,'user_id' => '46','school_id' => '1','created_at' => '2023-11-15 10:53:33','updated_at' => '2023-11-15 10:53:33'),
  array('id' => '846','module' => NULL,'sidebar_menu' => NULL,'old_id' => NULL,'section_id' => '1','parent_id' => '0','name' => 'Utilities','route' => 'utilities_section','parent_route' => NULL,'type' => NULL,'lang_name' => 'common.Utilities','icon' => NULL,'svg' => NULL,'status' => '1','menu_status' => '1','position' => '8','is_saas' => '0','relate_to_child' => '0','is_menu' => '1','is_admin' => '1','is_teacher' => '0','is_student' => '0','is_parent' => '0','created_by' => '1','updated_by' => '1','permission_section' => '1','alternate_module' => NULL,'user_id' => '46','school_id' => '1','created_at' => '2023-11-15 10:53:33','updated_at' => '2023-11-15 10:53:33'),
  array('id' => '847','module' => NULL,'sidebar_menu' => NULL,'old_id' => NULL,'section_id' => '1','parent_id' => '0','name' => 'Report','route' => 'report_section','parent_route' => NULL,'type' => NULL,'lang_name' => 'common.report_section','icon' => NULL,'svg' => NULL,'status' => '1','menu_status' => '1','position' => '8','is_saas' => '0','relate_to_child' => '0','is_menu' => '1','is_admin' => '1','is_teacher' => '0','is_student' => '0','is_parent' => '0','created_by' => '1','updated_by' => '1','permission_section' => '1','alternate_module' => NULL,'user_id' => '46','school_id' => '1','created_at' => '2023-11-15 10:53:33','updated_at' => '2023-11-15 10:53:33'),
  array('id' => '848','module' => NULL,'sidebar_menu' => NULL,'old_id' => NULL,'section_id' => '1','parent_id' => '0','name' => 'Settings Section','route' => 'settings_section','parent_route' => NULL,'type' => NULL,'lang_name' => 'common.settings_section','icon' => NULL,'svg' => NULL,'status' => '1','menu_status' => '1','position' => '8','is_saas' => '0','relate_to_child' => '0','is_menu' => '1','is_admin' => '1','is_teacher' => '0','is_student' => '0','is_parent' => '0','created_by' => '1','updated_by' => '1','permission_section' => '1','alternate_module' => NULL,'user_id' => '46','school_id' => '1','created_at' => '2023-11-15 10:53:33','updated_at' => '2023-11-15 10:53:33'),
  array('id' => '849','module' => NULL,'sidebar_menu' => NULL,'old_id' => NULL,'section_id' => '1','parent_id' => '0','name' => 'Module','route' => 'module_section','parent_route' => NULL,'type' => NULL,'lang_name' => 'common.module','icon' => NULL,'svg' => NULL,'status' => '1','menu_status' => '1','position' => '10','is_saas' => '0','relate_to_child' => '0','is_menu' => '1','is_admin' => '1','is_teacher' => '0','is_student' => '0','is_parent' => '0','created_by' => '1','updated_by' => '1','permission_section' => '1','alternate_module' => NULL,'user_id' => '46','school_id' => '1','created_at' => '2023-11-15 10:53:33','updated_at' => '2023-11-15 10:53:33'),
  array('id' => '850','module' => 'fees_collection','sidebar_menu' => 'fees','old_id' => NULL,'section_id' => '1','parent_id' => '0','name' => 'Assign Extra Curricular Fees','route' => 'fees_extra_class','parent_route' => 'fees_collection','type' => '2','lang_name' => 'fees.extra_class','icon' => NULL,'svg' => NULL,'status' => '1','menu_status' => '1','position' => '0','is_saas' => '0','relate_to_child' => '0','is_menu' => '1','is_admin' => '1','is_teacher' => '0','is_student' => '0','is_parent' => '0','created_by' => '1','updated_by' => '1','permission_section' => '0','alternate_module' => NULL,'user_id' => NULL,'school_id' => '1','created_at' => NULL,'updated_at' => NULL),
  array('id' => '851','module' => 'fees_collection','sidebar_menu' => 'fees','old_id' => NULL,'section_id' => '1','parent_id' => '0','name' => 'Collect Extra curricular Fees','route' => 'collect_extraclass_fees','parent_route' => 'fees_collection','type' => '2','lang_name' => 'fees.collect_extraclass_fees','icon' => NULL,'svg' => NULL,'status' => '1','menu_status' => '1','position' => '0','is_saas' => '0','relate_to_child' => '0','is_menu' => '1','is_admin' => '1','is_teacher' => '0','is_student' => '0','is_parent' => '0','created_by' => '1','updated_by' => '1','permission_section' => '0','alternate_module' => NULL,'user_id' => NULL,'school_id' => '1','created_at' => NULL,'updated_at' => NULL),
  array('id' => '852','module' => NULL,'sidebar_menu' => NULL,'old_id' => NULL,'section_id' => '1','parent_id' => '0','name' => 'Dashboard','route' => 'dashboard_section','parent_route' => NULL,'type' => NULL,'lang_name' => 'common.dashboard','icon' => NULL,'svg' => NULL,'status' => '1','menu_status' => '1','position' => '1','is_saas' => '0','relate_to_child' => '0','is_menu' => '1','is_admin' => '1','is_teacher' => '0','is_student' => '0','is_parent' => '0','created_by' => '1','updated_by' => '1','permission_section' => '1','alternate_module' => NULL,'user_id' => '65','school_id' => '1','created_at' => '2023-11-23 13:36:47','updated_at' => '2023-11-23 13:36:47'),
  array('id' => '853','module' => NULL,'sidebar_menu' => NULL,'old_id' => NULL,'section_id' => '1','parent_id' => '0','name' => 'Administration','route' => 'administration_section','parent_route' => NULL,'type' => NULL,'lang_name' => 'common.Administration','icon' => NULL,'svg' => NULL,'status' => '1','menu_status' => '1','position' => '8','is_saas' => '0','relate_to_child' => '0','is_menu' => '1','is_admin' => '1','is_teacher' => '0','is_student' => '0','is_parent' => '0','created_by' => '1','updated_by' => '1','permission_section' => '1','alternate_module' => NULL,'user_id' => '65','school_id' => '1','created_at' => '2023-11-23 13:36:47','updated_at' => '2023-11-23 13:36:47'),
  array('id' => '854','module' => NULL,'sidebar_menu' => NULL,'old_id' => NULL,'section_id' => '1','parent_id' => '0','name' => 'Student','route' => 'student_section','parent_route' => NULL,'type' => NULL,'lang_name' => 'common.student','icon' => NULL,'svg' => NULL,'status' => '1','menu_status' => '1','position' => '8','is_saas' => '0','relate_to_child' => '0','is_menu' => '1','is_admin' => '1','is_teacher' => '0','is_student' => '0','is_parent' => '0','created_by' => '1','updated_by' => '1','permission_section' => '1','alternate_module' => NULL,'user_id' => '65','school_id' => '1','created_at' => '2023-11-23 13:36:47','updated_at' => '2023-11-23 13:36:47'),
  array('id' => '855','module' => NULL,'sidebar_menu' => NULL,'old_id' => NULL,'section_id' => '1','parent_id' => '0','name' => 'Exam','route' => 'exam_section','parent_route' => NULL,'type' => NULL,'lang_name' => 'common.exam','icon' => NULL,'svg' => NULL,'status' => '1','menu_status' => '1','position' => '8','is_saas' => '0','relate_to_child' => '0','is_menu' => '1','is_admin' => '1','is_teacher' => '0','is_student' => '0','is_parent' => '0','created_by' => '1','updated_by' => '1','permission_section' => '1','alternate_module' => NULL,'user_id' => '65','school_id' => '1','created_at' => '2023-11-23 13:36:47','updated_at' => '2023-11-23 13:36:47'),
  array('id' => '856','module' => NULL,'sidebar_menu' => NULL,'old_id' => NULL,'section_id' => '1','parent_id' => '0','name' => 'Hr','route' => 'hr_section','parent_route' => NULL,'type' => NULL,'lang_name' => 'common.hr','icon' => NULL,'svg' => NULL,'status' => '1','menu_status' => '1','position' => '8','is_saas' => '0','relate_to_child' => '0','is_menu' => '1','is_admin' => '1','is_teacher' => '0','is_student' => '0','is_parent' => '0','created_by' => '1','updated_by' => '1','permission_section' => '1','alternate_module' => NULL,'user_id' => '65','school_id' => '1','created_at' => '2023-11-23 13:36:47','updated_at' => '2023-11-23 13:36:47'),
  array('id' => '857','module' => NULL,'sidebar_menu' => NULL,'old_id' => NULL,'section_id' => '1','parent_id' => '0','name' => 'Accounts','route' => 'accounts_section','parent_route' => NULL,'type' => NULL,'lang_name' => 'common.accounts','icon' => NULL,'svg' => NULL,'status' => '1','menu_status' => '1','position' => '8','is_saas' => '0','relate_to_child' => '0','is_menu' => '1','is_admin' => '1','is_teacher' => '0','is_student' => '0','is_parent' => '0','created_by' => '1','updated_by' => '1','permission_section' => '1','alternate_module' => NULL,'user_id' => '65','school_id' => '1','created_at' => '2023-11-23 13:36:47','updated_at' => '2023-11-23 13:36:47'),
  array('id' => '858','module' => NULL,'sidebar_menu' => NULL,'old_id' => NULL,'section_id' => '1','parent_id' => '0','name' => 'Utilities','route' => 'utilities_section','parent_route' => NULL,'type' => NULL,'lang_name' => 'common.Utilities','icon' => NULL,'svg' => NULL,'status' => '1','menu_status' => '1','position' => '8','is_saas' => '0','relate_to_child' => '0','is_menu' => '1','is_admin' => '1','is_teacher' => '0','is_student' => '0','is_parent' => '0','created_by' => '1','updated_by' => '1','permission_section' => '1','alternate_module' => NULL,'user_id' => '65','school_id' => '1','created_at' => '2023-11-23 13:36:47','updated_at' => '2023-11-23 13:36:47'),
  array('id' => '859','module' => NULL,'sidebar_menu' => NULL,'old_id' => NULL,'section_id' => '1','parent_id' => '0','name' => 'Report','route' => 'report_section','parent_route' => NULL,'type' => NULL,'lang_name' => 'common.report_section','icon' => NULL,'svg' => NULL,'status' => '1','menu_status' => '1','position' => '8','is_saas' => '0','relate_to_child' => '0','is_menu' => '1','is_admin' => '1','is_teacher' => '0','is_student' => '0','is_parent' => '0','created_by' => '1','updated_by' => '1','permission_section' => '1','alternate_module' => NULL,'user_id' => '65','school_id' => '1','created_at' => '2023-11-23 13:36:47','updated_at' => '2023-11-23 13:36:47'),
  array('id' => '860','module' => NULL,'sidebar_menu' => NULL,'old_id' => NULL,'section_id' => '1','parent_id' => '0','name' => 'Settings Section','route' => 'settings_section','parent_route' => NULL,'type' => NULL,'lang_name' => 'common.settings_section','icon' => NULL,'svg' => NULL,'status' => '1','menu_status' => '1','position' => '8','is_saas' => '0','relate_to_child' => '0','is_menu' => '1','is_admin' => '1','is_teacher' => '0','is_student' => '0','is_parent' => '0','created_by' => '1','updated_by' => '1','permission_section' => '1','alternate_module' => NULL,'user_id' => '65','school_id' => '1','created_at' => '2023-11-23 13:36:47','updated_at' => '2023-11-23 13:36:47'),
  array('id' => '861','module' => NULL,'sidebar_menu' => NULL,'old_id' => NULL,'section_id' => '1','parent_id' => '0','name' => 'Module','route' => 'module_section','parent_route' => NULL,'type' => NULL,'lang_name' => 'common.module','icon' => NULL,'svg' => NULL,'status' => '1','menu_status' => '1','position' => '10','is_saas' => '0','relate_to_child' => '0','is_menu' => '1','is_admin' => '1','is_teacher' => '0','is_student' => '0','is_parent' => '0','created_by' => '1','updated_by' => '1','permission_section' => '1','alternate_module' => NULL,'user_id' => '65','school_id' => '1','created_at' => '2023-11-23 13:36:47','updated_at' => '2023-11-23 13:36:47'),
  array('id' => '862','module' => NULL,'sidebar_menu' => 'human_resource','old_id' => NULL,'section_id' => '1','parent_id' => '0','name' => 'Payroll Settings','route' => 'payroll_settings','parent_route' => 'payroll','type' => '2','lang_name' => 'hr.payroll_settings','icon' => NULL,'svg' => NULL,'status' => '1','menu_status' => '1','position' => '9','is_saas' => '0','relate_to_child' => '0','is_menu' => '1','is_admin' => '1','is_teacher' => '0','is_student' => '0','is_parent' => '0','created_by' => '1','updated_by' => '1','permission_section' => '0','alternate_module' => NULL,'user_id' => NULL,'school_id' => '1','created_at' => NULL,'updated_at' => NULL),
  array('id' => '863','module' => '','sidebar_menu' => 'payroll','old_id' => NULL,'section_id' => '1','parent_id' => '0','name' => 'Payroll Generate','route' => 'payroll','parent_route' => 'payroll','type' => '2','lang_name' => 'hr.payroll_generate','icon' => NULL,'svg' => NULL,'status' => '1','menu_status' => '1','position' => '1','is_saas' => '0','relate_to_child' => '0','is_menu' => '1','is_admin' => '1','is_teacher' => '0','is_student' => '0','is_parent' => '0','created_by' => '1','updated_by' => '1','permission_section' => '0','alternate_module' => NULL,'user_id' => NULL,'school_id' => '1','created_at' => NULL,'updated_at' => NULL),
  array('id' => '864','module' => NULL,'sidebar_menu' => 'payroll','old_id' => NULL,'section_id' => '1','parent_id' => '0','name' => 'EPF Download','route' => 'download_epf_all','parent_route' => 'payroll','type' => '1','lang_name' => 'hr.download_epf','icon' => NULL,'svg' => NULL,'status' => '1','menu_status' => '1','position' => '1','is_saas' => '0','relate_to_child' => '0','is_menu' => '1','is_admin' => '1','is_teacher' => '0','is_student' => '0','is_parent' => '0','created_by' => '1','updated_by' => '1','permission_section' => '0','alternate_module' => NULL,'user_id' => NULL,'school_id' => '1','created_at' => NULL,'updated_at' => NULL),
  array('id' => '865','module' => NULL,'sidebar_menu' => 'accounts','old_id' => NULL,'section_id' => '1','parent_id' => '0','name' => 'Accounts Management','route' => 'account_management','parent_route' => 'accounts','type' => '3','lang_name' => 'accounts.account_management','icon' => NULL,'svg' => NULL,'status' => '1','menu_status' => '1','position' => '1','is_saas' => '0','relate_to_child' => '0','is_menu' => '1','is_admin' => '1','is_teacher' => '0','is_student' => '0','is_parent' => '0','created_by' => '1','updated_by' => '1','permission_section' => '0','alternate_module' => NULL,'user_id' => NULL,'school_id' => '1','created_at' => NULL,'updated_at' => NULL)
);

DB::table('permissions')->insert($permissions);
    }
}
